# TCL File Generated by Component Editor 9.0
# Mon Mar 12 11:46:53 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_slave_exram_8bit "avalon_slave_exram_8bit" v1.0
# | null 2012.03.12.11:46:53
# | 
# | 
# | D:/804/net_ctrl/avalon_slave_exram_8bit.v
# | 
# |    ./avalon_slave_exram_8bit.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module avalon_slave_exram_8bit
# | 
set_module_property NAME avalon_slave_exram_8bit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME avalon_slave_exram_8bit
set_module_property TOP_LEVEL_HDL_FILE avalon_slave_exram_8bit.v
set_module_property TOP_LEVEL_HDL_MODULE avalon_slave_exram_8bit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon_slave_exram_8bit.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point in_avs
# | 
add_interface in_avs avalon end
set_interface_property in_avs addressAlignment DYNAMIC
set_interface_property in_avs bridgesToMaster ""
set_interface_property in_avs burstOnBurstBoundariesOnly false
set_interface_property in_avs holdTime 0
set_interface_property in_avs isMemoryDevice false
set_interface_property in_avs isNonVolatileStorage false
set_interface_property in_avs linewrapBursts false
set_interface_property in_avs maximumPendingReadTransactions 0
set_interface_property in_avs printableDevice false
set_interface_property in_avs readLatency 1
set_interface_property in_avs readWaitStates 0
set_interface_property in_avs readWaitTime 0
set_interface_property in_avs setupTime 0
set_interface_property in_avs timingUnits Cycles
set_interface_property in_avs writeWaitTime 0

set_interface_property in_avs ASSOCIATED_CLOCK clock_reset
set_interface_property in_avs ENABLED true

add_interface_port in_avs in_avs_chipselect_n chipselect_n Input 1
add_interface_port in_avs in_avs_write_n write_n Input 1
add_interface_port in_avs in_avs_read_n read_n Input 1
add_interface_port in_avs in_avs_address address Input 16
add_interface_port in_avs in_avs_writedata writedata Input 8
add_interface_port in_avs in_avs_readdata readdata Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end wr_n export Output 1
add_interface_port conduit_end rd_n export Output 1
add_interface_port conduit_end addr export Output 16
add_interface_port conduit_end wdata export Output 8
add_interface_port conduit_end rdata export Input 8
# | 
# +-----------------------------------
